# Meta Data for SEO

## Homepage
title = "Home"
titleSeparator = "-"
titleAddition = "BizKit Technologies, Inc."
description = "BizKit's documentation site."

## Open Graph + Twitter Cards
images = ["bizkit.jpg"]
facebookAuthor = "BizKitTechnologies"
facebookPublisher = "BizKitTechnologies"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "bizkit.png"
schemaLinkedIn = "https://www.linkedin.com/company/bizkit-technologies-inc/"
schemaGitHub = "https://github.com/BizKit-Tech"
schemaSection = "docs"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://github.com/\">GitHub</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/BizKit-Tech/BizKit-Tech.github.io"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = true
  highLight = true
  kaTex = false
  collapsibleSidebar = true
